export const Question = [
    { id:1,
      Question: 'what is react ?',
      Answer: 'React is a front-end and open-source JavaScript library which is useful in developing user interfaces specifically for applications with a single page.',
    },
    { id:2,
      Question: ' What are the limitations of React?',
      Answer: 'React is not a full-blown framework as it is only a library.The components of React are numerous and will take time to fully grasp the benefits of all.',
    },
    { id:3,
      Question: ' What is useState() in React?',
      Answer: 'The useState() is a built-in React Hook that allows you for having state variables in functional components.',
    },
    { id:4,
      Question: 'What are keys in React?',
      Answer: 'A key is a special string attribute that needs to be included when using lists of elements.',
    },
    { id:5, 
      Question: 'What is JSX',
      Answer: 'JSX stands for JavaScript XML. It allows us to write HTML inside JavaScript and place them in the DOM without using functions like appendChild( ) or createElement( ).',
    },
    ]